### ISSUE TITLE
Inline styles causing issues

### ISSUE THREAD

**Issue by seanmccay** [AllenFang/react-bootstrap-table#1724]
There are inline styles of `height: 100%` for the divs with classes `react-bs-table react-bs-table-bordered` and the `react-bs-container-body` this produces a weird/undesirable rendering in the theme I'm using ( the container stretches past the table contents toward the bottom of the page ). Turning off the inline styles in dev tools fixes the table for me. 

Here are some examples of the issue:
![10-per-page](https://user-images.githubusercontent.com/19294231/32180708-b7b601a2-bd60-11e7-8090-7e4190442dfb.JPG)
![25-per-page](https://user-images.githubusercontent.com/19294231/32180725-c24fb068-bd60-11e7-821a-b9813db0e21b.JPG)

Why are there inline styles there? And how do you recommend clearing them out?

**Comment by seanmccay** [comment]
For now, I've done this to override the inline styles
```css
/* fix for react-bootstrap-table's inline height styles */
.react-bs-table.react-bs-table-bordered[style],
.react-bs-container-body[style] {
    height: inherit !important;
}
```
