### ISSUE TITLE
select row border

### ISSUE THREAD

**Issue by wenit123** [AllenFang/react-bootstrap-table#642]
How can I style the border of the row that i select.
So I can get something like in the pic.

![screen shot 2016-08-18 at 11 36 21 am](https://cloud.githubusercontent.com/assets/16068081/17786084/3ec52178-6538-11e6-817b-b0821e6c5c1f.png)

**Comment by AllenFang** [comment]
unn, I've no idea about your pic.. what's that?  could you please mark it or show the whole pic?

**Comment by wenit123** [comment]
![screen shot 2016-08-19 at 8 46 39 am](https://cloud.githubusercontent.com/assets/16068081/17815524/87cac3e4-65e9-11e6-8f56-70a380720f3e.png)


here is the mock up of the table.  thank you :)

**Comment by AllenFang** [comment]
@wenit123, the border it from ```.react-bs-table: { border: 1px solid #ddd }```  so It's hard to achieve your requirement.

You can try the following example to find some way:

```js
/* eslint max-len: 0 */
import React from 'react';
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';


const products = [];

function addProducts(quantity) {
  const startId = products.length;
  for (let i = 0; i < quantity; i++) {
    const id = startId + i;
    products.push({
      id: id,
      name: 'Item name ' + id,
      price: 2100 + i
    });
  }
}

addProducts(10);

// function trClassFormat(rowData, rIndex) {
//   return rIndex % 3 === 0 ? 'tr-function-example' : '';
// }

export default class BorderlessTable extends React.Component {


  constructor(props) {
    super(props);
    this.state = {
      selectedRowKey: ''
    };
  }

  trClassFormat = rowData => {
    // if is selected row, add a class name, so you can control the style on this row by class name
    return rowData.id === this.state.selectedRowKey ? 'tr-function-example' : '';
  }

  onSelect = (row, isSelected) => {
    if (isSelected) {
      this.setState({
        selectedRowKey: row.id
      });
    }
  }

  render() {
    const selectRow = {
      mode: 'radio',
      onSelect: this.onSelect
    };
    return (
      <BootstrapTable data={ products } bordered={ false } selectRow={ selectRow } trClassName={ this.trClassFormat }>
          <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
}
```

**Comment by AllenFang** [comment]
BTW, there are some [example](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/style) to show how to style your table

**Comment by AllenFang** [comment]
@wenit123, I try out the following solution, give a try :)
```js
/* eslint max-len: 0 */
import React from 'react';
import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';
require('./test.css');

const products = [];

function addProducts(quantity) {
  const startId = products.length;
  for (let i = 0; i < quantity; i++) {
    const id = startId + i;
    products.push({
      id: id,
      name: 'Item name ' + id,
      price: 2100 + i
    });
  }
}

addProducts(10);

export default class BorderlessTable extends React.Component {


  constructor(props) {
    super(props);
    this.state = {
      selectedRowKey: ''
    };
  }

  trClassFormat = rowData => {
    return rowData.id === this.state.selectedRowKey ? 'tr-no-border-example' : 'tr-border-example';
  }

  onSelect = (row, isSelected) => {
    if (isSelected) {
      this.setState({
        selectedRowKey: row.id
      });
    }
  }

  render() {
    const selectRow = {
      mode: 'radio',
      onSelect: this.onSelect
    };
    return (
      <BootstrapTable data={ products } bordered={ true } selectRow={ selectRow } trClassName={ this.trClassFormat }>
          <TableHeaderColumn dataField='id' isKey={ true }>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
}
```

test.css
```css
.tr-string-example{
    font-style: oblique;
    color: red;
    background-color: aquamarine;
}



.react-bs-table {
  border-width: 0px;
  border-top-width: 1px;
  border-left-width: 1px;
  /*border-right-width: 1px; */
}

.react-bs-table .table-bordered > thead > tr > th:last-child {
  border-right-width: 1px !important;
}

.tr-no-border-example{
    font-weight: bold;
    background-color: #ddd;
    border-right-width: 0px !important;
}

.tr-border-example{
    border-right: 1px solid #ddd !important;
    /*border-right-width: 1px !important;*/
}
```
