### ISSUE TITLE
Support for Bootstrap 4?

### ISSUE THREAD

**Issue by istanishev** [AllenFang/react-bootstrap-table#779]
Hi,

Any plans to support Bootstrap 4 soon ?

Cheers,
Ivan

**Comment by AllenFang** [comment]
HI @istanishev, this should be done at the future, but for now, I'm focus on the customization for this component, so after ```v3.0.0``` released and being stability, I'll spend some time to support Bootstrap@4. 

PR is welcome :)

Thanks

**Comment by madeinfree** [comment]
I can help this.

**Comment by konekoya** [comment]
As far as I know Bootstrap 4 is still in its Alpha version
http://blog.getbootstrap.com/2016/09/05/bootstrap-4-alpha-4/

There's no exact release date yet
https://github.com/mdo/ama/issues/146

`classes and features will change until we go beta`
https://github.com/mdo/ama/issues/223

hope these help :)

**Comment by AllenFang** [comment]
thanks @madeinfree :)  You can do it if you have free time, hope you dont spend too much times on it.
@konekoya , nice sharing, I need to study it cause of I dont event know what it look like.. QQ

**Comment by TechnicalBro** [comment]
Despite bootstrap 4 being alpha I'm a bit bold, so I'll be working on a patch / hack to support it until release.
Will edit this comment with a link and be submitting a PR as soon as It's complete. Or Functional :)

**Comment by AllenFang** [comment]
@TechnicalBro, thanks for contribution :)

**Comment by achepey** [comment]
Are there any updates on this?

**Comment by AllenFang** [comment]
@achepey, I think `react-bootstrap-table` is not fully support bootstrap@4 yet. but you can still try it and check if there's any critical issues, for me, this integration is not in my schedule in near future.

**Comment by iaincollins** [comment]
As this might be outstanding for a while, if it's helpful to anyone who is using Bootstrap 4, this is the CSS I came up with for react-bootstrap-table. I'm using reactstrap, which is great but Bootstrap 4 only.

I've included a screenshot to show how it renders. The dropdown menu works fine too with the couple of SCSS specific lines at the bottom (but you could just override those too).

Everything seems to work just fine, including responsive behaviour for the pagination controls.

![example](https://user-images.githubusercontent.com/595695/27412787-03416a40-56ef-11e7-938b-70619ae3f92b.png)

**My BootstrapTable options:**

```javascript
const options = {
  sizePerPage: 10,
  paginationSize: 5,
  sizePerPageList: [ {
      text: '5', value: 5
    }, {
      text: '10', value: 10
    }, {
      text: '20', value: 20
    }, {
      text: '100', value: 100
    }, {
      text: '500', value: 500
    } ]
}
```

**My CSS:**

```css
/* Hacks to provide react-bootstrap-table compatiblity with Bootstrap 4 */
.react-bs-table-pagination .col-md-6 {
  display: inline-block !important;
  clear: none;
}
.react-bs-table-pagination .col-md-6:first-child {
  float: left;
}
.react-bs-table-pagination .row {
  display: block;
}
.react-bs-table-pagination .react-bootstrap-table-page-btns-ul .page-item {
  float: left;
}
/* These lines use SCSS @extend feature to map Bootstrap 3 classes to Bootstrap 4 classes */
.react-bs-table-pagination .dropdown-menu li a {
  @extend .dropdown-item;
}
.btn-default {
  @extend .btn-secondary;
}
```
