### ISSUE TITLE
Get rid of all borders

### ISSUE THREAD

**Issue by kakariko-village** [AllenFang/react-bootstrap-table#820]
Hi i want to remove all border for table. I set bordered={false}, even set border:none!important for .react-bs-table but there're still the border bottom of each row. I cannot find where to remove them.

**Comment by AllenFang** [comment]
@kakariko-village, ```react-bootstrap-table``` only have the ```bordered``` props, so if you want to make all table borderless, you need to use some css to overwrite it.

```css
.react-bs-container-body tr {
  border-top-style: hidden !important;
}

.react-bs-container-header tr {
  border-bottom-style: hidden !important;
}
```
