### ISSUE TITLE
overflow of cell

### ISSUE THREAD

**Issue by edulis8** [AllenFang/react-bootstrap-table#839]
Hello,
I noticed that without a dataFormat function, the text contents of a cell will be appended with '...' before overflowing off the cell. However, once I put a dataFormat function, the ... disappears. I would love to know how to get those dots back.

**Comment by AllenFang** [comment]
@edulis8, because I use the text overflow like following:
```css
.react-bs-table table td,
.react-bs-table table th {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}
```

**Comment by AllenFang** [comment]
@edulis8, because I use the text overflow like following:
```css
.react-bs-table table td,
.react-bs-table table th {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}
```

I think in your case, you data format is not a pure text. so maybe you can show your formatter and I can try to help you :)
