### ISSUE TITLE
Animation on row expand

### ISSUE THREAD

**Issue by ptitFicus** [AllenFang/react-bootstrap-table#928]
I really love the new expandable-row feature, however I got an issue with it : I can't manage to animate the contraction of a row.

I succeeded to animate the expansion using the following code : 
```css
@keyframes EXPAND {
    0% { height: 0; }
    100% { height: 300px; }
}

.react-bs-container-body tr:nth-child(2n+2):not([hidden]) td div {
    animation: EXPAND 1s;
    height: 300px;
}
```
This code isn't great but does the job, however I haven't been able to animate contraction using the same method.

I think it's because the `hidden` attribute is added instantly to the `tr` element before any animation can be performed.

Any idea ?
